### ISSUE TITLE
[Bug]: Performance issues with high spawn rates.

### ISSUE THREAD

**Issue by ccrvincent** [Fuzss/magnumtorch#3] opened 2022-08-06 16:26 UTC
### Mod Loader (Required)

Forge

### Minecraft Version (Required)

1.18.2

### Mod Version (Required)

3.1.3

### Notes (Required)

Relaying from a report in a community support venue.

Modpack: Medieval MC Forge 1.18.2

Spark profile: https://spark.lucko.me/SkhViZ9I30

Server admin says the issue only happens while someone is in the End after some End Crystals were destroyed.  `MobSpawningHandler#anyInRange` is taking up 80% of the tick loop. 

Not sure how much of the issue is from the naturally high spawn rate of Endermen and how much is from modpack mechanics adding new spawns.

**Comment by Fuzss** [comment] 2022-10-10 11:33
Seems to be related to the spawning of [Cosmic Cod](https://alexs-mobs-bestiary.fandom.com/wiki/Cosmic_Cod) from Alex's Mobs.

**Comment by kyragit** [comment] 2023-03-02 04:05
I believe I have found the culprit! It's Savage Ender Dragon. For whatever reason, that mod causes huge lag spawning the Cosmic Cod near the central end island, and since Magnum Torch intercepts all spawns, it gets blamed by spark despite not being the root cause.

**Comment by Fuzss** [comment] 2023-03-26 19:07
That's interesting, I still decided to blacklist Cosmic Cod by default which definitely helps. Closing this now though since this seems to be the best I can do.

**Closed as completed by Fuzss** 2023-03-26 19:07 UTC
Labels: bug
